# Change these first
owner: nicko170
repo: status.devlan.io

sites:
  - name: Plesk Sydney Hosting
    url: https://plesk01.syd.devlan.io
  - name: RFSPager Website
    url: https://rfspager.app
  - name: RFSPager App Backend
    url: https://rfspager.app/graphql


status-website:
  cname: status.devlan.io
  logoUrl: https://raw.githubusercontent.com/nicko170/status.devlan.io/master/assets/logo.svg
  name: DevLAN.io Status Page
  introTitle: DevLAN.io Status Page
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
