name: Setup CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Update response time
        uses: upptime/uptime-monitor@v1.27.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ steps.generate-token.outputs.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.27.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ steps.generate-token.outputs.token }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ steps.generate-token.outputs.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.27.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ steps.generate-token.outputs.token }}
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: GitHub Pages Deploy
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: "site/status-page/__sapper__/export/"
          user_name: "Upptime Bot"
          user_email: "nicko170-bot@users.noreply.github.com"
