name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.27.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ steps.generate-token.outputs.token }}
